# Data Preparation

## Import Libraries

In [2]:
import numpy as np
import pandas as pd

## Import Data
The dataset contains all available data for more than 800,000 consumer loans issued from 2007 to 2015 by Lending Club: a large US peer-to-peer lending company. There are several different versions of this dataset. We have used a version available on kaggle.com. You can find it here: https://www.kaggle.com/wendykan/lending-club-loan-data/version/1
We divided the data into two periods because we assume that some data are available at the moment when we need to build Expected Loss models, and some data comes from applications after. Later, we investigate whether the applications we have after we built the Probability of Default (PD) model have similar characteristics with the applications we used to build the PD model.

In [3]:
loan_data_backup = pd.read_csv('loan_data_2007_2014.csv')

C:\Users\ETC\AppData\Local\Temp\ipykernel_7404\2954675577.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_backup = pd.read_csv('loan_data_2007_2014.csv')

In [4]:
loan_data = loan_data_backup.copy().drop(columns='Unnamed: 0')

## Explore Data

In [5]:
loan_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,...,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,...,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [6]:
pd.options.display.max_columns = None
#pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.

In [7]:
loan_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.00,0.00,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.00,0.00,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.00,0.00,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.90,766.90,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.0,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.00,0.00,0.00,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.00,0.00,0.00,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.00,0.00,0.00,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.00,0.00,0.00,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.00,0.00,0.00,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [8]:
loan_data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
loan_data.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.0,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.0,0.0,0.0,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.0,0.0,0.0,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.0,0.0,0.0,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.0,0.0,0.0,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.0,0.0,0.0,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [10]:
loan_data.columns.values
# Displays all column names.

array(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m'], dtype=object)

In [11]:
loan_data.select_dtypes(include=['object']).columns

Index(['term', 'grade', 'sub_grade', 'emp_title', 'emp_length',
       'home_ownership', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'earliest_cr_line', 'initial_list_status', 'last_pymnt_d',
       'next_pymnt_d', 'last_credit_pull_d', 'application_type'],
      dtype='object')

In [12]:
loan_data.info()
# Displays column names, complete (non-missing) cases per column, and datatype per column.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 74 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           466285 non-null  int64
 1   member_id                    466285 non-null  int64
 2   loan_amnt                    466285 non-null  int64
 3   funded_amnt                  466285 non-null  int64
 4   funded_amnt_inv              466285 non-null  float64
 5   term                         466285 non-null  object
 6   int_rate                     466285 non-null  float64
 7   installment                  466285 non-null  float64
 8   grade                        466285 non-null  object
 9   sub_grade                    466285 non-null  object
 10  emp_title                    438697 non-null  object
 11  emp_length                   445277 non-null  object
 12  home_ownership               466285 non-null  object
 13  annual_inc                   466281 non-null  float64
 14  verification_status          466285 non-null  object
 15  issue_d                      466285 non-null  object
 16  loan_status                  466285 non-null  object
 17  pymnt_plan                   466285 non-null  object
 18  url                          466285 non-null  object
 19  desc                         125981 non-null  object
 20  purpose                      466285 non-null  object
 21  title                        466264 non-null  object
 22  zip_code                     466285 non-null  object
 23  addr_state                   466285 non-null  object
 24  dti                          466285 non-null  float64
 25  delinq_2yrs                  466256 non-null  float64
 26  earliest_cr_line             466256 non-null  object
 27  inq_last_6mths               466256 non-null  float64
 28  mths_since_last_delinq       215934 non-null  float64
 29  mths_since_last_record       62638 non-null   float64
 30  open_acc                     466256 non-null  float64
 31  pub_rec                      466256 non-null  float64
 32  revol_bal                    466285 non-null  int64
 33  revol_util                   465945 non-null  float64
 34  total_acc                    466256 non-null  float64
 35  initial_list_status          466285 non-null  object
 36  out_prncp                    466285 non-null  float64
 37  out_prncp_inv                466285 non-null  float64
 38  total_pymnt                  466285 non-null  float64
 39  total_pymnt_inv              466285 non-null  float64
 40  total_rec_prncp              466285 non-null  float64
 41  total_rec_int                466285 non-null  float64
 42  total_rec_late_fee           466285 non-null  float64
 43  recoveries                   466285 non-null  float64
 44  collection_recovery_fee      466285 non-null  float64
 45  last_pymnt_d                 465909 non-null  object
 46  last_pymnt_amnt              466285 non-null  float64
 47  next_pymnt_d                 239071 non-null  object
 48  last_credit_pull_d           466243 non-null  object
 49  collections_12_mths_ex_med   466140 non-null  float64
 50  mths_since_last_major_derog  98974 non-null   float64
 51  policy_code                  466285 non-null  int64
 52  application_type             466285 non-null  object
 53  annual_inc_joint             0 non-null       float64
 54  dti_joint                    0 non-null       float64
 55  verification_status_joint    0 non-null       float64
 56  acc_now_delinq               466256 non-null  float64
 57  tot_coll_amt                 396009 non-null  float64
 58  tot_cur_bal                  396009 non-null  float64
 59  open_acc_6m                  0 non-null       float64
 60  open_il_6m                   0 non-null       float64
 61  open_il_12m                  0 non-null       float64
 62  open_il_24m                  0 non-null       float64
 63  mths_since_rcnt_il           0 non-null       float64
 64  total_bal_il                 0 non-null       float64
 65  il_util                      0 non-null       float64
 66  open_rv_12m                  0 non-null       float64
 67  open_rv_24m                  0 non-null       float64
 68  max_bal_bc                   0 non-null       float64
 69  all_util                     0 non-null       float64
 70  total_rev_hi_lim             396009 non-null  float64
 71  inq_fi                       0 non-null       float64
 72  total_cu_tl                  0 non-null       float64
 73  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(6), object(22)
memory usage: 263.3+ MB

In [13]:
loan_data.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
count,4.662850e+05,4.662850e+05,466285.000000,466285.000000,466285.000000,466285.000000,466285.000000,4.662810e+05,466285.000000,466256.000000,466256.000000,215934.000000,62638.000000,466256.000000,466256.000000,4.662850e+05,465945.000000,466256.000000,466285.000000,466285.000000,466285.000000,466285.000000,466285.000000,466285.000000,466285.000000,466285.000000,466285.000000,466285.000000,466140.000000,98974.000000,466285.0,0.0,0.0,0.0,466256.000000,3.960090e+05,3.960090e+05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.960090e+05,0.0,0.0,0.0
mean,1.307973e+07,1.459766e+07,14317.277577,14291.801044,14222.329888,13.829236,432.061201,7.327738e+04,17.218758,0.284678,0.804745,34.104430,74.306012,11.187069,0.160564,1.623020e+04,56.176947,25.064430,4410.062342,4408.452258,11540.686220,11469.892747,8866.014657,2588.677225,0.650129,85.344211,8.961534,3123.913796,0.009085,42.852547,1.0,NaN,NaN,NaN,0.004002,1.919135e+02,1.388017e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.037909e+04,NaN,NaN,NaN
std,1.089371e+07,1.168237e+07,8286.509164,8274.371300,8297.637788,4.357587,243.485550,5.496357e+04,7.851121,0.797365,1.091598,21.778487,30.357653,4.987526,0.510863,2.067625e+04,23.732628,11.600141,6355.078769,6353.198001,8265.627112,8254.157579,7031.687997,2483.809661,5.265730,552.216084,85.491437,5554.737393,0.108648,21.662591,0.0,NaN,NaN,NaN,0.068637,1.463021e+04,1.521147e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.724713e+04,NaN,NaN,NaN
min,5.473400e+04,7.047300e+04,500.000000,500.000000,0.000000,5.420000,15.670000,1.896000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,NaN,NaN,NaN,0.000000,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN
25%,3.639987e+06,4.379705e+06,8000.000000,8000.000000,8000.000000,10.990000,256.690000,4.500000e+04,11.360000,0.000000,0.000000,16.000000,53.000000,8.000000,0.000000,6.413000e+03,39.200000,17.000000,0.000000,0.000000,5552.125349,5499.250000,3708.560000,957.280000,0.000000,0.000000,0.000000,312.620000,0.000000,26.000000,1.0,NaN,NaN,NaN,0.000000,0.000000e+00,2.861800e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.350000e+04,NaN,NaN,NaN
50%,1.010790e+07,1.194108e+07,12000.000000,12000.000000,12000.000000,13.660000,379.890000,6.300000e+04,16.870000,0.000000,0.000000,31.000000,76.000000,10.000000,0.000000,1.176400e+04,57.600000,23.000000,441.470000,441.380000,9419.250943,9355.430000,6817.760000,1818.880000,0.000000,0.000000,0.000000,545.960000,0.000000,42.000000,1.0,NaN,NaN,NaN,0.000000,0.000000e+00,8.153900e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.280000e+04,NaN,NaN,NaN
75%,2.073121e+07,2.300154e+07,20000.000000,20000.000000,19950.000000,16.490000,566.580000,8.896000e+04,22.780000,0.000000,1.000000,49.000000,102.000000,14.000000,0.000000,2.033300e+04,74.700000,32.000000,7341.650000,7338.390000,15308.158460,15231.310000,12000.000000,3304.530000,0.000000,0.000000,0.000000,3187.510000,0.000000,59.000000,1.0,NaN,NaN,NaN,0.000000,0.000000e+00,2.089530e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.790000e+04,NaN,NaN,NaN
max,3.809811e+07,4.086083e+07,35000.000000,35000.000000,35000.000000,26.060000,1409.990000,7.500000e+06,39.990000,29.000000,33.000000,188.000000,129.000000,84.000000,63.000000,2.568995e+06,892.300000,156.000000,32160.380000,32160.380000,57777.579870,57777.580000,35000.030000,24205.620000,358.680000,33520.270000,7002.190000,36234.440000,20.000000,188.000000,1.0,NaN,NaN,NaN,5.000000,9.152545e+06,8.000078e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999999e+06,NaN,NaN,NaN

# Proprocessing

## Preprocessing few continuous variables

In [14]:
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '6 years', '2 years', '7 years', nan],
      dtype=object)

In [15]:
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('+ years','')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('<','')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years','')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year','')

loan_data['emp_length_int']

0         10
1          1
2         10
3         10
4          1
          ..
466280     4
466281    10
466282     7
466283     3
466284    10
Name: emp_length_int, Length: 466285, dtype: object

In [16]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [17]:
loan_data['emp_length_int'].dtype

dtype('float64')

In [18]:
loan_data['earliest_cr_line']

0         Jan-85
1         Apr-99
2         Nov-01
3         Feb-96
4         Jan-96
           ...
466280    Apr-03
466281    Jun-97
466282    Dec-01
466283    Feb-03
466284    Feb-00
Name: earliest_cr_line, Length: 466285, dtype: object

In [19]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'],format= '%b-%y')

In [20]:
loan_data['earliest_cr_line_date']

0        1985-01-01
1        1999-04-01
2        2001-11-01
3        1996-02-01
4        1996-01-01
            ...
466280   2003-04-01
466281   1997-06-01
466282   2001-12-01
466283   2003-02-01
466284   2000-02-01
Name: earliest_cr_line_date, Length: 466285, dtype: datetime64[ns]

In [21]:
pd.to_datetime('2024-09-02') - loan_data['earliest_cr_line_date']

0        14489 days
1         9286 days
2         8341 days
3        10441 days
4        10472 days
            ...
466280    7825 days
466281    9955 days
466282    8311 days
466283    7884 days
466284    8980 days
Name: earliest_cr_line_date, Length: 466285, dtype: timedelta64[ns]

In [22]:
avg_day_in_month = 30.44
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2024-09-02') - loan_data['earliest_cr_line_date']).dt.days) / avg_day_in_month)
loan_data['mths_since_earliest_cr_line'].describe()

count    466256.000000
mean        320.482430
std          93.974829
min        -531.000000
25%         264.000000
50%         306.000000
75%         366.000000
max         668.000000
Name: mths_since_earliest_cr_line, dtype: float64

In [23]:
loan_data.loc[:,['earliest_cr_line','earliest_cr_line_date','mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line'] < 0]
#actual years is in 19s

       earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
1580             Sep-62            2062-09-01                       -456.0
1770             Sep-68            2068-09-01                       -528.0
2799             Sep-64            2064-09-01                       -480.0
3282             Sep-67            2067-09-01                       -516.0
3359             Feb-65            2065-02-01                       -485.0
...                 ...                   ...                          ...
464003           Jan-68            2068-01-01                       -520.0
464260           Jul-66            2066-07-01                       -502.0
465100           Oct-67            2067-10-01                       -517.0
465500           Sep-67            2067-09-01                       -516.0
465655           Jan-56            2056-01-01                       -376.0

[1169 rows x 3 columns]

In [24]:
loan_data['mths_since_earliest_cr_line'][loan_data['mths_since_earliest_cr_line'] < 0] = loan_data['mths_since_earliest_cr_line'].max()

C:\Users\ETC\AppData\Local\Temp\ipykernel_7404\2332624952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan_data['mths_since_earliest_cr_line'][loan_data['mths_since_earliest_cr_line'] < 0] = loan_data['mths_since_earliest_cr_line'].max()

In [25]:
min(loan_data['mths_since_earliest_cr_line'])

154.0

In [26]:
loan_data['term']

0          36 months
1          60 months
2          36 months
3          36 months
4          60 months
             ...
466280     60 months
466281     60 months
466282     60 months
466283     36 months
466284     36 months
Name: term, Length: 466285, dtype: object

In [27]:
loan_data['term_int'] = pd.to_numeric(loan_data['term'].str.replace("months",""))
loan_data['term_int'].dtype

dtype('int64')

In [28]:
loan_data['mths_since_issue_d'] = pd.to_datetime(loan_data['issue_d'],format="%b-%y")
loan_data['mths_since_issue_d']

0        2011-12-01
1        2011-12-01
2        2011-12-01
3        2011-12-01
4        2011-12-01
            ...
466280   2014-01-01
466281   2014-01-01
466282   2014-01-01
466283   2014-01-01
466284   2014-01-01
Name: mths_since_issue_d, Length: 466285, dtype: datetime64[ns]

In [29]:
pd.to_datetime('2024-09-02')  - loan_data['mths_since_issue_d']

0        4659 days
1        4659 days
2        4659 days
3        4659 days
4        4659 days
            ...
466280   3897 days
466281   3897 days
466282   3897 days
466283   3897 days
466284   3897 days
Name: mths_since_issue_d, Length: 466285, dtype: timedelta64[ns]

In [30]:
loan_data['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2024-09-02') - loan_data['mths_since_issue_d']).dt.days)/avg_day_in_month)
loan_data['mths_since_issue_d'].describe()

count    466285.000000
mean        132.255187
std          14.340154
min         117.000000
25%         122.000000
50%         128.000000
75%         138.000000
max         207.000000
Name: mths_since_issue_d, dtype: float64

## Preprocessing few discrete variables

In [31]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 79 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           466285 non-null  int64
 1   member_id                    466285 non-null  int64
 2   loan_amnt                    466285 non-null  int64
 3   funded_amnt                  466285 non-null  int64
 4   funded_amnt_inv              466285 non-null  float64
 5   term                         466285 non-null  object
 6   int_rate                     466285 non-null  float64
 7   installment                  466285 non-null  float64
 8   grade                        466285 non-null  object
 9   sub_grade                    466285 non-null  object
 10  emp_title                    438697 non-null  object
 11  emp_length                   445277 non-null  object
 12  home_ownership               466285 non-null  object
 13  annual_inc                   466281 non-null  float64
 14  verification_status          466285 non-null  object
 15  issue_d                      466285 non-null  object
 16  loan_status                  466285 non-null  object
 17  pymnt_plan                   466285 non-null  object
 18  url                          466285 non-null  object
 19  desc                         125981 non-null  object
 20  purpose                      466285 non-null  object
 21  title                        466264 non-null  object
 22  zip_code                     466285 non-null  object
 23  addr_state                   466285 non-null  object
 24  dti                          466285 non-null  float64
 25  delinq_2yrs                  466256 non-null  float64
 26  earliest_cr_line             466256 non-null  object
 27  inq_last_6mths               466256 non-null  float64
 28  mths_since_last_delinq       215934 non-null  float64
 29  mths_since_last_record       62638 non-null   float64
 30  open_acc                     466256 non-null  float64
 31  pub_rec                      466256 non-null  float64
 32  revol_bal                    466285 non-null  int64
 33  revol_util                   465945 non-null  float64
 34  total_acc                    466256 non-null  float64
 35  initial_list_status          466285 non-null  object
 36  out_prncp                    466285 non-null  float64
 37  out_prncp_inv                466285 non-null  float64
 38  total_pymnt                  466285 non-null  float64
 39  total_pymnt_inv              466285 non-null  float64
 40  total_rec_prncp              466285 non-null  float64
 41  total_rec_int                466285 non-null  float64
 42  total_rec_late_fee           466285 non-null  float64
 43  recoveries                   466285 non-null  float64
 44  collection_recovery_fee      466285 non-null  float64
 45  last_pymnt_d                 465909 non-null  object
 46  last_pymnt_amnt              466285 non-null  float64
 47  next_pymnt_d                 239071 non-null  object
 48  last_credit_pull_d           466243 non-null  object
 49  collections_12_mths_ex_med   466140 non-null  float64
 50  mths_since_last_major_derog  98974 non-null   float64
 51  policy_code                  466285 non-null  int64
 52  application_type             466285 non-null  object
 53  annual_inc_joint             0 non-null       float64
 54  dti_joint                    0 non-null       float64
 55  verification_status_joint    0 non-null       float64
 56  acc_now_delinq               466256 non-null  float64
 57  tot_coll_amt                 396009 non-null  float64
 58  tot_cur_bal                  396009 non-null  float64
 59  open_acc_6m                  0 non-null       float64
 60  open_il_6m                   0 non-null       float64
 61  open_il_12m                  0 non-null       float64
 62  open_il_24m                  0 non-null       float64
 63  mths_since_rcnt_il           0 non-null       float64
 64  total_bal_il                 0 non-null       float64
 65  il_util                      0 non-null       float64
 66  open_rv_12m                  0 non-null       float64
 67  open_rv_24m                  0 non-null       float64
 68  max_bal_bc                   0 non-null       float64
 69  all_util                     0 non-null       float64
 70  total_rev_hi_lim             396009 non-null  float64
 71  inq_fi                       0 non-null       float64
 72  total_cu_tl                  0 non-null       float64
 73  inq_last_12m                 0 non-null       float64
 74  emp_length_int               445277 non-null  float64
 75  earliest_cr_line_date        466256 non-null  datetime64[ns]
 76  mths_since_earliest_cr_line  466256 non-null  float64
 77  term_int                     466285 non-null  int64
 78  mths_since_issue_d           466285 non-null  float64
dtypes: datetime64[ns](1), float64(49), int64(7), object(22)
memory usage: 281.0+ MB

In [32]:
pd.get_dummies(loan_data['grade'])

            A      B      C      D      E      F      G
0       False   True  False  False  False  False  False
1       False  False   True  False  False  False  False
2       False  False   True  False  False  False  False
3       False  False   True  False  False  False  False
4       False   True  False  False  False  False  False
...       ...    ...    ...    ...    ...    ...    ...
466280  False  False   True  False  False  False  False
466281  False  False  False   True  False  False  False
466282  False  False  False   True  False  False  False
466283   True  False  False  False  False  False  False
466284  False  False  False   True  False  False  False

[466285 rows x 7 columns]

In [33]:
pd.get_dummies(loan_data['grade'],prefix='grade',prefix_sep=':')

        grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  grade:G
0         False     True    False    False    False    False    False
1         False    False     True    False    False    False    False
2         False    False     True    False    False    False    False
3         False    False     True    False    False    False    False
4         False     True    False    False    False    False    False
...         ...      ...      ...      ...      ...      ...      ...
466280    False    False     True    False    False    False    False
466281    False    False    False     True    False    False    False
466282    False    False    False     True    False    False    False
466283     True    False    False    False    False    False    False
466284    False    False    False     True    False    False    False

[466285 rows x 7 columns]

In [34]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'],prefix='grade',prefix_sep=':'),
                     pd.get_dummies(loan_data['sub_grade'],prefix='sub_grade',prefix_sep=':'),
                     pd.get_dummies(loan_data['home_ownership'],prefix='home_ownership',prefix_sep=':'),
                     pd.get_dummies(loan_data['verification_status'],prefix='verification_status',prefix_sep=':'),
                     pd.get_dummies(loan_data['loan_status'],prefix='loan_status',prefix_sep=':'),
                     pd.get_dummies(loan_data['purpose'],prefix='purpose',prefix_sep=':'),
                     pd.get_dummies(loan_data['addr_state'],prefix='addr_state',prefix_sep=':'),
                     pd.get_dummies(loan_data['initial_list_status'],prefix='initial_list_status',prefix_sep=':'),
                     
                     
                     
                    ]

loan_data_dummies

[        grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  grade:G
 0         False     True    False    False    False    False    False
 1         False    False     True    False    False    False    False
 2         False    False     True    False    False    False    False
 3         False    False     True    False    False    False    False
 4         False     True    False    False    False    False    False
 ...         ...      ...      ...      ...      ...      ...      ...
 466280    False    False     True    False    False    False    False
 466281    False    False    False     True    False    False    False
 466282    False    False    False     True    False    False    False
 466283     True    False    False    False    False    False    False
 466284    False    False    False     True    False    False    False

 [466285 rows x 7 columns],
         sub_grade:A1  sub_grade:A2  sub_grade:A3  sub_grade:A4  sub_grade:A5  \
 0              False         False         False         False         False
 1              False         False         False         False         False
 2              False         False         False         False         False
 3              False         False         False         False         False
 4              False         False         False         False         False
 ...              ...           ...           ...           ...           ...
 466280         False         False         False         False         False
 466281         False         False         False         False         False
 466282         False         False         False         False         False
 466283         False         False         False          True         False
 466284         False         False         False         False         False

         sub_grade:B1  sub_grade:B2  sub_grade:B3  sub_grade:B4  sub_grade:B5  \
 0              False          True         False         False         False
 1              False         False         False         False         False
 2              False         False         False         False         False
 3              False         False         False         False         False
 4              False         False         False         False          True
 ...              ...           ...           ...           ...           ...
 466280         False         False         False         False         False
 466281         False         False         False         False         False
 466282         False         False         False         False         False
 466283         False         False         False         False         False
 466284         False         False         False         False         False

         sub_grade:C1  sub_grade:C2  sub_grade:C3  sub_grade:C4  sub_grade:C5  \
 0              False         False         False         False         False
 1              False         False         False          True         False
 2              False         False         False         False          True
 3               True         False         False         False         False
 4              False         False         False         False         False
 ...              ...           ...           ...           ...           ...
 466280         False          True         False         False         False
 466281         False         False         False         False         False
 466282         False         False         False         False         False
 466283         False         False         False         False         False
 466284         False         False         False         False         False

         sub_grade:D1  sub_grade:D2  sub_grade:D3  sub_grade:D4  sub_grade:D5  \
 0              False         False         False         False         False
 1              False         False         False         False         False
 2              False         False         False         False         False
 3              False         False         False         False         False
 4              False         False         False         False         False
 ...              ...           ...           ...           ...           ...
 466280         False         False         False         False         False
 466281         False         False         False         False          True
 466282          True         False         False         False         False
 466283         False         False         False         False         False
 466284         False         False          True         False         False

         sub_grade:E1  sub_grade:E2  sub_grade:E3  sub_grade:E4  sub_grade:E5  \
 0              False         False         False         False         False
 1              False         False         False         False         False
 2              False         False         False         False         False
 3              False         False         False         False         False
 4              False         False         False         False         False
 ...              ...           ...           ...           ...           ...
 466280         False         False         False         False         False
 466281         False         False         False         False         False
 466282         False         False         False         False         False
 466283         False         False         False         False         False
 466284         False         False         False         False         False

         sub_grade:F1  sub_grade:F2  sub_grade:F3  sub_grade:F4  sub_grade:F5  \
 0              False         False         False         False         False
 1              False         False         False         False         False
 2              False         False         False         False         False
 3              False         False         False         False         False
 4              False         False         False         False         False
 ...              ...           ...           ...           ...           ...
 466280         False         False         False         False         False
 466281         False         False         False         False         False
 466282         False         False         False         False         False
 466283         False         False         False         False         False
 466284         False         False         False         False         False

         sub_grade:G1  sub_grade:G2  sub_grade:G3  sub_grade:G4  sub_grade:G5
 0              False         False         False         False         False
 1              False         False         False         False         False
 2              False         False         False         False         False
 3              False         False         False         False         False
 4              False         False         False         False         False
 ...              ...           ...           ...           ...           ...
 466280         False         False         False         False         False
 466281         False         False         False         False         False
 466282         False         False         False         False         False
 466283         False         False         False         False         False
 466284         False         False         False         False         False

 [466285 rows x 35 columns],
         home_ownership:ANY  home_ownership:MORTGAGE  home_ownership:NONE  \
 0                    False                    False                False
 1                    False                    False                False
 2                    False                    False                False
 3                    False                    False                False
 4                    False                    False                False
 ...                    ...                      ...                  ...
 466280               False                     True                False
 466281               False                     True                False
 466282               False                     True                False
 466283               False                    False                False
 466284               False                     True                False

         home_ownership:OTHER  home_ownership:OWN  home_ownership:RENT
 0                      False               False                 True
 1                      False               False                 True
 2                      False               False                 True
 3                      False               False                 True
 4                      False               False                 True
 ...                      ...                 ...                  ...
 466280                 False               False                False
 466281                 False               False                False
 466282                 False               False                False
 466283                 False                True                False
 466284                 False               False                False

 [466285 rows x 6 columns],
         verification_status:Not Verified  verification_status:Source Verified  \
 0                                  False                                False
 1                                  False                                 True
 2                                   True                                False
 3                                  False                                 True
 4                                  False                                 True
 ...                                  ...                                  ...
 466280                             False                                 True
 466281                             False                                False
 466282                             False                                False
 466283                             False                                False
 466284                             False                                False

         verification_status:Verified
 0                               True
 1                              False
 2                              False
 3                              False
 4                              False
 ...                              ...
 466280                         False
 466281                          True
 466282                          True
 466283                          True
 466284                          True

 [466285 rows x 3 columns],
         loan_status:Charged Off  loan_status:Current  loan_status:Default  \
 0                         False                False                False
 1                          True                False                False
 2                         False                False                False
 3                         False                False                False
 4                         False                 True                False
 ...                         ...                  ...                  ...
 466280                    False                 True                False
 466281                     True                False                False
 466282                    False                 True                False
 466283                    False                False                False
 466284                    False                 True                False

         loan_status:Does not meet the credit policy. Status:Charged Off  \
 0                                                   False
 1                                                   False
 2                                                   False
 3                                                   False
 4                                                   False
 ...                                                   ...
 466280                                              False
 466281                                              False
 466282                                              False
 466283                                              False
 466284                                              False

         loan_status:Does not meet the credit policy. Status:Fully Paid  \
 0                                                   False
 1                                                   False
 2                                                   False
 3                                                   False
 4                                                   False
 ...                                                   ...
 466280                                              False
 466281                                              False
 466282                                              False
 466283                                              False
 466284                                              False

         loan_status:Fully Paid  loan_status:In Grace Period  \
 0                         True                        False
 1                        False                        False
 2                         True                        False
 3                         True                        False
 4                        False                        False
 ...                        ...                          ...
 466280                   False                        False
 466281                   False                        False
 466282                   False                        False
 466283                    True                        False
 466284                   False                        False

         loan_status:Late (16-30 days)  loan_status:Late (31-120 days)
 0                               False                           False
 1                               False                           False
 2                               False                           False
 3                               False                           False
 4                               False                           False
 ...                               ...                             ...
 466280                          False                           False
 466281                          False                           False
 466282                          False                           False
 466283                          False                           False
 466284                          False                           False

 [466285 rows x 9 columns],
         purpose:car  purpose:credit_card  purpose:debt_consolidation  \
 0             False                 True                       False
 1              True                False                       False
 2             False                False                       False
 3             False                False                       False
 4             False                False                       False
 ...             ...                  ...                         ...
 466280        False                False                        True
 466281        False                False                        True
 466282        False                False                        True
 466283        False                 True                       False
 466284        False                False                       False

         purpose:educational  purpose:home_improvement  purpose:house  \
 0                     False                     False          False
 1                     False                     False          False
 2                     False                     False          False
 3                     False                     False          False
 4                     False                     False          False
 ...                     ...                       ...            ...
 466280                False                     False          False
 466281                False                     False          False
 466282                False                     False          False
 466283                False                     False          False
 466284                False                     False          False

         purpose:major_purchase  purpose:medical  purpose:moving  \
 0                        False            False           False
 1                        False            False           False
 2                        False            False           False
 3                        False            False           False
 4                        False            False           False
 ...                        ...              ...             ...
 466280                   False            False           False
 466281                   False            False           False
 466282                   False            False           False
 466283                   False            False           False
 466284                   False            False           False

         purpose:other  purpose:renewable_energy  purpose:small_business  \
 0               False                     False                   False
 1               False                     False                   False
 2               False                     False                    True
 3                True                     False                   False
 4                True                     False                   False
 ...               ...                       ...                     ...
 466280          False                     False                   False
 466281          False                     False                   False
 466282          False                     False                   False
 466283          False                     False                   False
 466284           True                     False                   False

         purpose:vacation  purpose:wedding
 0                  False            False
 1                  False            False
 2                  False            False
 3                  False            False
 4                  False            False
 ...                  ...              ...
 466280             False            False
 466281             False            False
 466282             False            False
 466283             False            False
 466284             False            False

 [466285 rows x 14 columns],
         addr_state:AK  addr_state:AL  addr_state:AR  addr_state:AZ  \
 0               False          False          False           True
 1               False          False          False          False
 2               False          False          False          False
 3               False          False          False          False
 4               False          False          False          False
 ...               ...            ...            ...            ...
 466280          False          False          False          False
 466281          False          False          False          False
 466282          False          False          False          False
 466283          False          False          False          False
 466284          False          False          False          False

         addr_state:CA  addr_state:CO  addr_state:CT  addr_state:DC  \
 0               False          False          False          False
 1               False          False          False          False
 2               False          False          False          False
 3                True          False          False          False
 4               False          False          False          False
 ...               ...            ...            ...            ...
 466280          False          False          False          False

In [35]:
loan_data_dummies = pd.concat(loan_data_dummies,axis=1)

In [36]:
type(loan_data_dummies)

pandas.core.frame.DataFrame

In [37]:
loan_data = pd.concat([loan_data,loan_data_dummies],axis=1)
loan_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,earliest_cr_line_date,mths_since_earliest_cr_line,term_int,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.00,0.00,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1985-01-01,476.0,36,153.0,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1999-04-01,305.0,60,153.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.00,0.00,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2001-11-01,274.0,36,153.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.00,0.00,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1996-02-01,343.0,36,153.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.90,766.90,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1996-01-01,344.0,60,153.0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.0,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.00,0.00,0.00,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN,4.0,2003-04-01,257.0,60,128.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True
466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.00,0.00,0.00,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN,10.0,1997-06-01,327.0,60,128.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.00,0.00,0.00,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN,7.0,2001-12-01,273.0,60,128.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.00,0.00,0.00,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN,3.0,2003-02-01,259.0,36,128.0,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.00,0.00,0.00,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN,10.0,2000-02-01,295.0,36,128.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False

## Missing values and clean

In [38]:
loan_data.isnull()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,earliest_cr_line_date,mths_since_earliest_cr_line,term_int,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466281,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466282,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466283,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466284,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [39]:
pd.options.display.max_rows = None # show all columns
loan_data.isnull().sum()

id                                                                      0
member_id                                                               0
loan_amnt                                                               0
funded_amnt                                                             0
funded_amnt_inv                                                         0
term                                                                    0
int_rate                                                                0
installment                                                             0
grade                                                                   0
sub_grade                                                               0
emp_title                                                           27588
emp_length                                                          21008
home_ownership                                                          0
annual_inc                                                              4
verification_status                                                     0
issue_d                                                                 0
loan_status                                                             0
pymnt_plan                                                              0
url                                                                     0
desc                                                               340304
purpose                                                                 0
title                                                                  21
zip_code                                                                0
addr_state                                                              0
dti                                                                     0
delinq_2yrs                                                            29
earliest_cr_line                                                       29
inq_last_6mths                                                         29
mths_since_last_delinq                                             250351
mths_since_last_record                                             403647
open_acc                                                               29
pub_rec                                                                29
revol_bal                                                               0
revol_util                                                            340
total_acc                                                              29
initial_list_status                                                     0
out_prncp                                                               0
out_prncp_inv                                                           0
total_pymnt                                                             0
total_pymnt_inv                                                         0
total_rec_prncp                                                         0
total_rec_int                                                           0
total_rec_late_fee                                                      0
recoveries                                                              0
collection_recovery_fee                                                 0
last_pymnt_d                                                          376
last_pymnt_amnt                                                         0
next_pymnt_d                                                       227214
last_credit_pull_d                                                     42
collections_12_mths_ex_med                                            145
mths_since_last_major_derog                                        367311
policy_code                                                             0
application_type                                                        0
annual_inc_joint                                                   466285
dti_joint                                                          466285
verification_status_joint                                          466285
acc_now_delinq                                                         29
tot_coll_amt                                                        70276
tot_cur_bal                                                         70276
open_acc_6m                                                        466285
open_il_6m                                                         466285
open_il_12m                                                        466285
open_il_24m                                                        466285
mths_since_rcnt_il                                                 466285
total_bal_il                                                       466285
il_util                                                            466285
open_rv_12m                                                        466285
open_rv_24m                                                        466285
max_bal_bc                                                         466285
all_util                                                           466285
total_rev_hi_lim                                                    70276
inq_fi                                                             466285
total_cu_tl                                                        466285
inq_last_12m                                                       466285
emp_length_int                                                      21008
earliest_cr_line_date                                                  29
mths_since_earliest_cr_line                                            29
term_int                                                                0
mths_since_issue_d                                                      0
grade:A                                                                 0
grade:B                                                                 0
grade:C                                                                 0
grade:D                                                                 0
grade:E                                                                 0
grade:F                                                                 0
grade:G                                                                 0
sub_grade:A1                                                            0
sub_grade:A2                                                            0
sub_grade:A3                                                            0
sub_grade:A4                                                            0
sub_grade:A5                                                            0
sub_grade:B1                                                            0
sub_grade:B2                                                            0
sub_grade:B3                                                            0
sub_grade:B4                                                            0
sub_grade:B5                                                            0
sub_grade:C1                                                            0
sub_grade:C2                                                            0
sub_grade:C3                                                            0
sub_grade:C4                                                            0
sub_grade:C5                                                            0
sub_grade:D1                                                            0
sub_grade:D2                                                            0
sub_grade:D3                                                            0
sub_grade:D4                                                            0
sub_grade:D5                                                            0
sub_grade:E1                                                            0
sub_grade:E2                                                            0
sub_grade:E3                                                            0
sub_grade:E4                                                            0
sub_grade:E5                                                            0
sub_grade:F1                                                            0
sub_grade:F2                                                            0
sub_grade:F3                                                            0
sub_grade:F4                                                            0
sub_grade:F5                                                            0
sub_grade:G1                                                            0
sub_grade:G2                                                            0
sub_grade:G3                                                            0
sub_grade:G4                                                            0
sub_grade:G5                                                            0
home_ownership:ANY                                                      0
home_ownership:MORTGAGE                                                 0
home_ownership:NONE                                                     0
home_ownership:OTHER                                                    0
home_ownership:OWN                                                      0
home_ownership:RENT                                                     0
verification_status:Not Verified                                        0
verification_status:Source Verified                                     0
verification_status:Verified                                            0
loan_status:Charged Off                                                 0
loan_status:Current                                                     0
loan_status:Default                                                     0
loan_status:Does not meet the credit policy. Status:Charged Off         0
loan_status:Does not meet the credit policy. Status:Fully Paid          0
loan_status:Fully Paid                                                  0
loan_status:In Grace Period                                             0
loan_status:Late (16-30 days)                                           0
loan_status:Late (31-120 days)                                          0
purpose:car                                                             0
purpose:credit_card                                                     0
purpose:debt_consolidation                                              0
purpose:educational                                                     0
purpose:home_improvement                                                0
purpose:house                                                           0
purpose:major_purchase                                                  0
purpose:medical                                                         0
purpose:moving                                                          0
purpose:other                                                           0
purpose:renewable_energy                                                0
purpose:small_business                                                  0
purpose:vacation                                                        0
purpose:wedding                                                         0
addr_state:AK                                                           0
addr_state:AL                                                           0
addr_state:AR                                                           0
addr_state:AZ                                                           0
addr_state:CA                                                           0
addr_state:CO                                                           0
addr_state:CT                                                           0
addr_state:DC                                                           0
addr_state:DE                                                           0
addr_state:FL                                                           0
addr_state:GA                                                           0
addr_state:HI                                                           0
addr_state:IA                                                           0
addr_state:ID                                                           0
addr_state:IL                                                           0
addr_state:IN                                                           0
addr_state:KS                                                           0
addr_state:KY                                                           0
addr_state:LA                                                           0
addr_state:MA                                                           0
addr_state:MD                                                           0
addr_state:ME                                                           0
addr_state:MI                                                           0
addr_state:MN                                                           0
addr_state:MO                                                           0
addr_state:MS                                                           0
addr_state:MT                                                           0
addr_state:NC                                                           0
addr_state:NE                                                           0
addr_state:NH                                                           0
addr_state:NJ                                                           0
addr_state:NM                                                           0
addr_state:NV                                                           0
addr_state:NY                                                           0
addr_state:OH                                                           0
addr_state:OK                                                           0
addr_state:OR                                                           0
addr_state:PA                                                           0
addr_state:RI                                                           0
addr_state:SC                                                           0
addr_state:SD                                                           0
addr_state:TN                                                           0
addr_state:TX                                                           0
addr_state:UT                                                           0
addr_state:VA                                                           0
addr_state:VT                                                           0
addr_state:WA                                                           0
addr_state:WI                                                           0
addr_state:WV                                                           0
addr_state:WY                                                           0
initial_list_status:f                                                   0
initial_list_status:w                                                   0
dtype: int64

In [40]:
pd.options.display.max_rows = 100

In [41]:
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace= True)

In [42]:
loan_data['total_rev_hi_lim'].isnull().sum()

0

In [43]:
loan_data.loc[loan_data['annual_inc'].isnull(), 'annual_inc']

42449   NaN
42450   NaN
42480   NaN
42533   NaN
Name: annual_inc, dtype: float64

In [44]:
loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean(), inplace=True)

In [45]:
loan_data['mths_since_earliest_cr_line'].fillna(0, inplace=True) 
loan_data['acc_now_delinq'].fillna(0, inplace=True)
loan_data['total_acc'].fillna(0, inplace=True)
loan_data['pub_rec'].fillna(0, inplace=True)
loan_data['open_acc'].fillna(0, inplace=True)
loan_data['inq_last_6mths'].fillna(0, inplace=True)
loan_data['delinq_2yrs'].fillna(0, inplace=True)
loan_data['emp_length_int'].fillna(0, inplace=True)

# PD model

## Data preparation

### Dependent Variable.Good/Bad (Default) Definition. Default and Non-default Accounts

In [47]:
loan_data['loan_status'].isnull().sum()

0

In [49]:
loan_data['loan_status'].unique()

array(['Fully Paid', 'Charged Off', 'Current', 'Default',
       'Late (31-120 days)', 'In Grace Period', 'Late (16-30 days)',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

### meaning of loan_status

Fully Paid: การชำระเงินของเงินกู้ได้ถูกจ่ายเต็มจำนวนโดยผู้กู้แล้ว และไม่มีการชำระเงินเพิ่มเติมที่ค้างอยู่

Charged Off: ผู้ให้กู้ได้ตัดหนี้ออกเป็นขาดทุนเพราะเชื่อว่าผู้กู้จะไม่ชำระหนี้คืน ซึ่งมักจะเกิดขึ้นหลังจากช่วงเวลานานของการไม่ชำระเงิน

Current: เงินกู้ได้รับการชำระตามกำหนดเรียบร้อยแล้ว และผู้กู้กำลังปฏิบัติตามข้อผูกพันการชำระเงินทั้งหมดตามกำหนด

Default: ผู้กู้ล้มเหลวในการชำระเงินตามข้อตกลงเงินกู้ และเงินกู้ถือว่ามีความผิดพลาดร้ายแรง การนิยามของการผิดนัดอาจแตกต่างกันไป แต่โดยทั่วไปหมายถึงการละเมิดข้อตกลงเงินกู้ที่สำคัญ

Late (31-120 days): การชำระเงินของเงินกู้ล่าช้า 31 ถึง 120 วัน สถานะนี้หมายความว่าผู้กู้ได้พลาดการชำระเงิน แต่ยังไม่ถึงระดับการผิดนัด

In Grace Period: เงินกู้อยู่ในช่วงระยะเวลาผ่อนผันที่ผู้กู้พลาดการชำระเงิน แต่ได้รับเวลามากขึ้นในการชำระเงินโดยไม่ต้องเผชิญกับบทลงโทษหรือผิดนัด

Late (16-30 days): การชำระเงินของเงินกู้ล่าช้า 16 ถึง 30 วัน สถานะนี้หมายถึงความผิดพลาดในระยะสั้นที่ผู้กู้ได้พลาดการชำระเงินหนึ่งหรือมากกว่าหนึ่งครั้ง แต่ยังไม่ถึงระดับการผิดนัดที่ร้ายแรง

Does not meet the credit policy. Status: Fully Paid: สถานะนี้หมายความว่าแม้ว่าเงินกู้จะได้รับการชำระเต็มจำนวน แต่ไม่ตรงตามข้อกำหนดนโยบายเครดิตในบางช่วงเวลาของชีวิตเงินกู้ ซึ่งอาจบ่งบอกว่าเงินกู้ได้รับการชำระแล้ว แต่ถูกจัดอยู่ในปัญหานโยบายเครดิตระหว่างช่วงเวลาหนึ่ง

Does not meet the credit policy. Status: Charged Off: สถานะนี้หมายความว่าเงินกู้ถูกตัดออกเป็นขาดทุนและไม่ตรงตามข้อกำหนดนโยบายเครดิต ซึ่งแสดงว่าเงินกู้ถูกเขียนออกและถูกติดป้ายว่าผิดนโยบายเครดิต

In [51]:
loan_data['loan_status'].value_counts()/loan_data['loan_status'].count()

loan_status
Current                                                0.480878
Fully Paid                                             0.396193
Charged Off                                            0.091092
Late (31-120 days)                                     0.014798
In Grace Period                                        0.006747
Does not meet the credit policy. Status:Fully Paid     0.004263
Late (16-30 days)                                      0.002612
Default                                                0.001784
Does not meet the credit policy. Status:Charged Off    0.001632
Name: count, dtype: float64

In [52]:
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off','Default',
                                                                'Does not meet the credit policy. Status:Charged Off ',
                                                                'Late (31-120 days) ']), 0,1)
# if isin that list will assign to 0 if not is 1

In [53]:
loan_data['good_bad']

0         1
1         0
2         1
3         1
4         1
         ..
466280    1
466281    0
466282    1
466283    1
466284    1
Name: good_bad, Length: 466285, dtype: int32

## splitting Data

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
train_test_split(loan_data.drop('good_bad',axis=1),loan_data['good_bad'])

[              id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
 6995      889630    1106164      15000        15000          15000.0
 383739  17132611   19255160       3500         3500           3500.0
 278239  31227277   33800504      24000        24000          24000.0
 425234  12995796   15027999      16000        16000          16000.0
 99290    6818560    6338859      15000        15000          15000.0
 ...          ...        ...        ...          ...              ...
 131237   5637146    7019434      12000        12000          12000.0
 50845    9665554   11517647      30000        30000          30000.0
 324036  16070847   18173346      16500        16500          16500.0
 322581  24715771   27158668      16000        16000          16000.0
 407334  14638878   16701205      10000        10000          10000.0

               term  int_rate  installment grade sub_grade  \
 6995     36 months      6.62       460.56     A        A2
 383739   36 months     11.67       115.70     B        B4
 278239   36 months      9.17       765.10     B        B1
 425234   60 months     14.16       373.63     C        C2
 99290    60 months     24.89       439.31     F        F4
 ...            ...       ...          ...   ...       ...
 131237   60 months     15.31       287.44     C        C2
 50845    60 months     16.99       745.42     D        D1
 324036   60 months     12.99       375.35     C        C1
 322581   36 months     14.49       550.66     C        C4
 407334   36 months     12.49       334.49     B        B4

                       emp_title emp_length home_ownership  annual_inc  \
 6995    Oregon State University    3 years       MORTGAGE     55000.0
 383739  Customer service writer    5 years           RENT     75000.0
 278239       Healthcare Analyst    2 years       MORTGAGE     75000.0
 425234    High School Counselor  10+ years       MORTGAGE     55000.0
 99290               Le Colonial  10+ years           RENT     60000.0
 ...                         ...        ...            ...         ...
 131237          Jp Morgan chase    3 years       MORTGAGE     66000.0
 50845                 Detective  10+ years       MORTGAGE     67000.0
 324036      Development Manager    6 years            OWN     65000.0
 322581          General manager    6 years       MORTGAGE     75000.0
 407334         Engineering Lead    8 years           RENT     73000.0

        verification_status issue_d loan_status pymnt_plan  \
 6995       Source Verified  Sep-11  Fully Paid          n
 383739        Not Verified  May-14     Current          n
 278239            Verified  Oct-14     Current          n
 425234     Source Verified  Mar-14     Current          n
 99290             Verified  Sep-13  Fully Paid          n
 ...                    ...     ...         ...        ...
 131237     Source Verified  Jun-13  Fully Paid          n
 50845      Source Verified  Dec-13     Current          n
 324036     Source Verified  Aug-14     Current          n
 322581     Source Verified  Aug-14     Current          n
 407334            Verified  Apr-14     Current          n

                                                       url  \
 6995    https://www.lendingclub.com/browse/loanDetail....
 383739  https://www.lendingclub.com/browse/loanDetail....
 278239  https://www.lendingclub.com/browse/loanDetail....
 425234  https://www.lendingclub.com/browse/loanDetail....
 99290   https://www.lendingclub.com/browse/loanDetail....
 ...                                                   ...
 131237  https://www.lendingclub.com/browse/loanDetail....
 50845   https://www.lendingclub.com/browse/loanDetail....
 324036  https://www.lendingclub.com/browse/loanDetail....
 322581  https://www.lendingclub.com/browse/loanDetail....
 407334  https://www.lendingclub.com/browse/loanDetail....

                                                      desc             purpose  \
 6995                                                  NaN         credit_card
 383739                                                NaN         credit_card
 278239                                                NaN  debt_consolidation
 425234                                                NaN         credit_card
 99290     Borrower added on 08/20/13 > This loan will ...         credit_card
 ...                                                   ...                 ...
 131237    Borrower added on 05/30/13 > To pay credit c...         credit_card
 50845     Borrower added on 12/09/13 > this loan is to...         credit_card
 324036                                                NaN         credit_card
 322581                                                NaN  debt_consolidation
 407334                                                NaN         credit_card

                                    title zip_code addr_state    dti  \
 6995                  Credit CardRidance    973xx         OR   7.16
 383739           Credit card refinancing    750xx         TX  13.92
 278239                Debt consolidation    761xx         TX  11.22
 425234           Credit card refinancing    750xx         TX  20.23
 99290   5 Year Credit Card Pay-off Plan!    606xx         IL  19.16
 ...                                  ...      ...        ...    ...
 131237                     Personal loan    330xx         FL  20.41
 50845            Credit card refinancing    707xx         LA  25.49
 324036           Credit card refinancing    631xx         MO  15.60
 322581                Debt consolidation    070xx         NJ  17.82
 407334           Credit card refinancing    672xx         KS   7.23

         delinq_2yrs earliest_cr_line  inq_last_6mths  mths_since_last_delinq  \
 6995            0.0           Jul-93             0.0                     NaN
 383739          0.0           Aug-08             1.0                     NaN
 278239          0.0           Jul-02             1.0                     NaN
 425234          0.0           Aug-96             2.0                     NaN
 99290           0.0           Oct-00             2.0                     NaN
 ...             ...              ...             ...                     ...
 131237          0.0           Jan-02             1.0                    60.0
 50845           0.0           Mar-96             1.0                     NaN
 324036          0.0           Jul-01             0.0                     NaN
 322581          1.0           Jul-01             1.0                     3.0
 407334          0.0           Dec-10             1.0                     NaN

         mths_since_last_record  open_acc  pub_rec  revol_bal  revol_util  \
 6995                       NaN       4.0      0.0      14228        33.5
 383739                     NaN       6.0      0.0       5675        73.7
 278239                     NaN      23.0      0.0      23662        37.9
 425234                   110.0      12.0      1.0      14820        56.8
 99290                      NaN      14.0      0.0      18688        93.7
 ...                        ...       ...      ...        ...         ...
 131237                   116.0      12.0      1.0      22478        57.2
 50845                      NaN       6.0      0.0      18688        82.0
 324036                     NaN      14.0      0.0      16351        41.2
 322581                    38.0       8.0      1.0       6424        34.7
 407334                     NaN       9.0      0.0       5810        50.1

         total_acc initial_list_status  out_prncp  out_prncp_inv  total_pymnt  \
 6995         11.0                   f       0.00           0.00  16441.93000
 383739        8.0                   f    1804.83        1804.83   2198.30000
 278239       34.0                   f   15439.06       15439.06  10699.17000
 425234       18.0                   w   11624.44       11624.44   7846.23000
 99290        20.0                   f       0.00           0.00  18819.81928
 ...           ...                 ...        ...            ...          ...
 131237       19.0                   f       0.00           0.00  15744.24999
 50845        23.0                   f   20461.21       20461.21  18635.30000
 324036       24.0                   f   12849.54       12849.54   6380.95000
 322581       27.0                   f    9299.17        9299.17   9361.22000
 407334       10.0                   f    4623.04        4623.04   7024.29000

         total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
 6995           16441.93         15000.00        1441.93                 0.0
 383739          2198.30          1695.17         503.13                 0.0
 278239         10699.17          8560.94        2138.23                 0.0
 425234          7846.23          4375.56        3470.67                 0.0
 99290          18819.82         15000.00        3819.82                 0.0
 ...                 ...              ...            ...                 ...
 131237         15744.25         12000.00        3744.25                 0.0
 50845          18635.30          9538.79        9096.51                 0.0
 324036          6380.95          3650.46        2730.49                 0.0
 322581          9361.22          6700.83        2660.39                 0.0
 407334          7024.29          5376.96        1647.33                 0.0

         recoveries  collection_recovery_fee last_pymnt_d  last_pymnt_amnt  \
 6995           0.0                      0.0       Dec-13          4946.89
 383739         0.0                      0.0       Dec-15           115.70
 278239         0.0                      0.0       Dec-15           765.10
 425234         0.0                      0.0       Dec-15           373.63
 99290          0.0                      0.0       Oct-14         13549.25
 ...            ...                      ...          ...              ...
 131237         0.0                      0.0       Nov-15          7695.93
 50845          0.0                      0.0       Jan-16           745.42
 324036         0.0                      0.0       Jan-16           375.35
 322581         0.0                      0.0       Jan-16           550.66
 407334         0.0                      0.0       Jan-16           334.49

        next_pymnt_d last_credit_pull_d  collections_12_mths_ex_med  \
 6995            NaN             Dec-13                         0.0
 383739       Feb-16             Jan-16                         0.0
 278239       Feb-16             Jan-16                         1.0
 425234       Feb-16             Jan-16                         0.0
 99290           NaN             Jan-16                         0.0
 ...             ...                ...                         ...
 131237          NaN             Dec-15                         0.0
 50845        Feb-16             Jan-16                         0.0
 324036       Feb-16             Jan-16                         0.0
 322581       Feb-16             Apr-15                         0.0
 407334       Feb-16             Jan-16                         0.0

         mths_since_last_major_derog  policy_code application_type  \
 6995                            NaN            1       INDIVIDUAL
 383739                          NaN            1       INDIVIDUAL
 278239                          NaN            1       INDIVIDUAL
 425234                          NaN            1       INDIVIDUAL
 99290                           NaN            1       INDIVIDUAL
 ...                             ...          ...              ...
 131237                          NaN            1       INDIVIDUAL
 50845                           NaN            1       INDIVIDUAL
 324036                          NaN            1       INDIVIDUAL
 322581                          NaN            1       INDIVIDUAL
 407334                          NaN            1       INDIVIDUAL

         annual_inc_joint  dti_joint  verification_status_joint  \
 6995                 NaN        NaN                        NaN
 383739               NaN        NaN                        NaN
 278239               NaN        NaN                        NaN
 425234               NaN        NaN                        NaN
 99290                NaN        NaN                        NaN
 ...                  ...        ...                        ...
 131237               NaN        NaN                        NaN
 50845                NaN        NaN                        NaN
 324036               NaN        NaN                        NaN
 322581               NaN        NaN                        NaN
 407334               NaN        NaN                        NaN

         acc_now_delinq  tot_coll_amt  tot_cur_bal  open_acc_6m  open_il_6m  \
 6995               0.0           NaN          NaN          NaN         NaN
 383739             0.0           0.0      23480.0          NaN         NaN
 278239             0.0         152.0     305520.0          NaN         NaN
 425234             0.0           0.0     145977.0          NaN         NaN
 99290              0.0           0.0      69177.0          NaN         NaN
 ...                ...           ...          ...          ...         ...
 131237             0.0           0.0     215116.0          NaN         NaN
 50845              0.0           0.0      52104.0          NaN         NaN
 324036             0.0           0.0      22815.0          NaN         NaN
 322581             0.0           0.0      26908.0          NaN         NaN
 407334             0.0           0.0      12231.0          NaN         NaN

         open_il_12m  open_il_24m  mths_since_rcnt_il  total_bal_il  il_util  \
 6995            NaN          NaN                 NaN           NaN      NaN
 383739          NaN          NaN                 NaN           NaN      NaN
 278239          NaN          NaN                 NaN           NaN      NaN
 425234          NaN          NaN                 NaN           NaN      NaN
 99290           NaN          NaN                 NaN           NaN      NaN
 ...             ...          ...                 ...           ...      ...
 131237          NaN          NaN                 NaN           NaN      NaN
 50845           NaN          NaN                 NaN           NaN      NaN
 324036          NaN          NaN                 NaN           NaN      NaN
 322581          NaN          NaN                 NaN           NaN      NaN
 407334          NaN          NaN                 NaN           NaN      NaN

         open_rv_12m  open_rv_24m  max_bal_bc  all_util  total_rev_hi_lim  \
 6995            NaN          NaN         NaN       NaN           15000.0
 383739          NaN          NaN         NaN       NaN            7700.0
 278239          NaN          NaN         NaN       NaN           62500.0
 425234          NaN          NaN         NaN       NaN           26100.0
 99290           NaN          NaN         NaN       NaN           19935.0
 ...             ...          ...         ...       ...               ...
 131237          NaN          NaN         NaN       NaN           39300.0
 50845           NaN          NaN         NaN       NaN           22800.0
 324036          NaN          NaN         NaN       NaN           39700.0
 322581          NaN          NaN         NaN       NaN           18500.0
 407334          NaN          NaN         NaN       NaN           11600.0

         inq_fi  total_cu_tl  inq_last_12m  emp_length_int  \
 6995       NaN          NaN           NaN             3.0
 383739     NaN          NaN           NaN             5.0
 278239     NaN          NaN           NaN             2.0
 425234     NaN          NaN           NaN            10.0
 99290      NaN          NaN           NaN            10.0
 ...        ...          ...           ...             ...
 131237     NaN          NaN           NaN             3.0
 50845      NaN          NaN           NaN            10.0
 324036     NaN          NaN           NaN             6.0
 322581     NaN          NaN           NaN             6.0
 407334     NaN          NaN           NaN             8.0

        earliest_cr_line_date  mths_since_earliest_cr_line  term_int  \
 6995              1993-07-01                        374.0        36
 383739            2008-08-01                        193.0        36
 278239            2002-07-01                        266.0        36
 425234            1996-08-01                        337.0        60
 99290             2000-10-01                        287.0        60
 ...                      ...                          ...       ...
 131237            2002-01-01                        272.0        60
 50845             1996-03-01                        342.0        60
 324036            2001-07-01                        278.0        60
 322581            2001-07-01                        278.0        36
 407334            2010-12-01                        165.0        36

         mths_since_issue_d  grade:A  grade:B  grade:C  grade:D  grade:E  \
 6995                 156.0     True    False    False    False    False
 383739               124.0    False     True    False    False    False
 278239               119.0    False     True    False    False    False
 425234               126.0    False    False     True    False    False
 99290                132.0    False    False    False    False    False
 ...                    ...      ...      ...      ...      ...      ...
 131237               135.0    False    False     True    False    False
 50845                129.0    False    False    False     True    False
 324036               121.0    False    False     True    False    False
 322581               121.0    False    False     True    False    False
 407334               125.0    False     True    False    False    False

         grade:F  grade:G  sub_grade:A1  sub_grade:A2  sub_grade:A3  \
 6995      False    False         False          True         False
 383739    False    False         False         False         False
 278239    False    False         False         False         False
 425234    False    False         False         False         False
 99290      True    False         False         False         False
 ...         ...      ...           ...           ...           ...
 131237    False    False         False         False         False
 50845     False    False         False         False         False
 324036    False    False         False         False         False
 322581    False    False         False         False         False
 407334    False    False         False         False         False

         sub_grade:A4  sub_grade:A5  sub_grade:B1  sub_grade:B2  sub_grade:B3  \
 6995           False         False         False         False         False
 383739         False         False         False         False         False
 278239         False         False          True         False         False
 425234         False         False         False         False         False
 99290          False         False         False         False         False
 ...              ...           ...           ...           ...           ...
 131237         False         False         False         False         False
 50845          False         False         False         False         False
 324036         False         False         False         False         False
 322581         False         False         False         False         False
 407334         False         False         False         False         False

         sub_grade:B4  sub_grade:B5  sub_grade:C1  sub_grade:C2  sub_grade:C3  \
 6995           False         False         False         False         False
 383739          True         False         False         False         False
 278239         False         False         False         False         False
 425234         False         False         False          True         False

In [70]:
loan_data_inputs_train,loan_data_inputs_test,loan_data_targets_train,loan_data_targets_test = train_test_split(loan_data.drop('good_bad',axis=1),loan_data['good_bad'],test_size=0.2,random_state=42)

In [71]:
loan_data_inputs_train.shape

(373028, 205)

In [72]:
loan_data_targets_train.shape

(373028,)

In [73]:
loan_data_inputs_test.shape

(93257, 205)

In [74]:
loan_data_targets_test.shape

(93257,)

### An Example (การคำนวณ Weight of Evidence (WoE) และ Information Value (IV) สำหรับตัวแปรเชิงหมวดหมู่ (grade))

In [75]:
df_inputs_prepr = loan_data_inputs_train
df_targets_prepr = loan_data_targets_train

grade:

คำอธิบาย: คอลัมน์นี้แทนค่าตัวแปรประเภทที่กำลังวิเคราะห์ เช่น เกรดของเงินกู้
การใช้งาน: ใช้ในการจัดกลุ่มข้อมูลและคำนวณสถิติต่าง ๆ สำหรับแต่ละหมวดหมู่

In [77]:
df_inputs_prepr['grade'].unique()

array(['A', 'C', 'D', 'B', 'E', 'F', 'G'], dtype=object)

In [78]:
df1 = pd.concat([df_inputs_prepr['grade'],df_targets_prepr],axis=1)
df1.head()

       grade  good_bad
427211     A         1
206088     C         1
136020     A         1
412305     D         1
36159      C         0

In [79]:
df1.groupby(df1.columns.values[0],as_index=False)[df1.columns.values[1]].count()

  grade  good_bad
0     A     59759
1     B    109730
2     C    100245
3     D     61498
4     E     28612
5     F     10530
6     G      2654

In [80]:
df1.groupby(df1.columns.values[0],as_index=False)[df1.columns.values[1]].mean()

  grade  good_bad
0     A  0.965578
1     B  0.931632
2     C  0.903496
3     D  0.870662
4     E  0.836572
5     F  0.789269
6     G  0.780332

In [81]:
df1 = pd.concat([df1.groupby(df1.columns.values[0],as_index=False)[df1.columns.values[1]].count(),
                 df1.groupby(df1.columns.values[0],as_index=False)[df1.columns.values[1]].mean()],axis=1)

In [84]:
df1 = df1.iloc[:,[0,1,3]]

In [85]:
df1

  grade  good_bad  good_bad
0     A     59759  0.965578
1     B    109730  0.931632
2     C    100245  0.903496
3     D     61498  0.870662
4     E     28612  0.836572
5     F     10530  0.789269
6     G      2654  0.780332

n_obs:

คำอธิบาย: จำนวนของการสังเกตสำหรับแต่ละเกรด
การใช้งาน: ใช้ในการคำนวณสัดส่วนของเงินกู้ดีและเงินกู้ไม่ดีสำหรับแต่ละเกรด แสดงถึงจำนวนรวมของเงินกู้สำหรับเกรดนั้น ๆ

prop_good:

คำอธิบาย: สัดส่วนของเงินกู้ที่ "ดี" (เช่น เงินกู้ที่ชำระเต็มจำนวน) สำหรับแต่ละเกรด
การใช้งาน: ใช้ในการคำนวณจำนวนเงินกู้ดีและไม่ดี และคำนวณสัดส่วนของเงินกู้ดีและไม่ดีสำหรับแต่ละเกรด

In [87]:
df1.columns = ['grade','n_obs','prop_good']
df1

  grade   n_obs  prop_good
0     A   59759   0.965578
1     B  109730   0.931632
2     C  100245   0.903496
3     D   61498   0.870662
4     E   28612   0.836572
5     F   10530   0.789269
6     G    2654   0.780332

In [88]:
df1['prop_n_obs'] = df1['n_obs']/df1['n_obs'].sum()

In [89]:
df1

  grade   n_obs  prop_good  prop_n_obs
0     A   59759   0.965578    0.160200
1     B  109730   0.931632    0.294160
2     C  100245   0.903496    0.268733
3     D   61498   0.870662    0.164862
4     E   28612   0.836572    0.076702
5     F   10530   0.789269    0.028228
6     G    2654   0.780332    0.007115

n_good:

คำอธิบาย: จำนวนจริงของเงินกู้ดีสำหรับแต่ละเกรด
การใช้งาน: คำนวณจาก prop_good คูณด้วย n_obs ใช้ในการคำนวณสัดส่วนของเงินกู้ดีและไม่ดี

n_bad:

คำอธิบาย: จำนวนจริงของเงินกู้ไม่ดีสำหรับแต่ละเกรด
การใช้งาน: คำนวณเป็น (1 - prop_good) คูณด้วย n_obs ใช้ในการคำนวณสัดส่วนและ WoE

In [94]:
df1['n_good'] = df1['prop_good']*df1['n_obs']
df1['n_bad'] = (1-df1['prop_good']) * df1['n_obs']
df1

  grade   n_obs  prop_good  prop_n_obs    n_good   n_bad
0     A   59759   0.965578    0.160200   57702.0  2057.0
1     B  109730   0.931632    0.294160  102228.0  7502.0
2     C  100245   0.903496    0.268733   90571.0  9674.0
3     D   61498   0.870662    0.164862   53544.0  7954.0
4     E   28612   0.836572    0.076702   23936.0  4676.0
5     F   10530   0.789269    0.028228    8311.0  2219.0
6     G    2654   0.780332    0.007115    2071.0   583.0

prop_n_good:

คำอธิบาย: สัดส่วนของเงินกู้ดีสำหรับแต่ละเกรดเทียบกับจำนวนรวมของเงินกู้ดีทั้งหมด
การใช้งาน: ใช้ในการคำนวณ WoE เพื่อเข้าใจว่าแต่ละเกรดมีส่วนร่วมในจำนวนเงินกู้ดีทั้งหมดมากแค่ไหน
prop_n_bad:

คำอธิบาย: สัดส่วนของเงินกู้ไม่ดีสำหรับแต่ละเกรดเทียบกับจำนวนรวมของเงินกู้ไม่ดีทั้งหมด
การใช้งาน: ใช้ในการคำนวณ WoE เพื่อเข้าใจว่าแต่ละเกรดมีส่วนร่วมในจำนวนเงินกู้ไม่ดีทั้งหมดมากแค่ไหน

In [95]:
df1['prop_n_good'] = df1['n_good'] / df1['n_good'].sum()
df1['prop_n_bad'] = df1['n_bad'] / df1['n_bad'].sum()
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad
0,A,59759,0.965578,0.160200,57702.0,2057.0,0.170533,0.059339
1,B,109730,0.931632,0.294160,102228.0,7502.0,0.302125,0.216414
2,C,100245,0.903496,0.268733,90571.0,9674.0,0.267674,0.279071
3,D,61498,0.870662,0.164862,53544.0,7954.0,0.158244,0.229453
4,E,28612,0.836572,0.076702,23936.0,4676.0,0.070741,0.134891
5,F,10530,0.789269,0.028228,8311.0,2219.0,0.024562,0.064013
6,G,2654,0.780332,0.007115,2071.0,583.0,0.006121,0.016818

Weight of Evidence (WoE) เป็นตัวชี้วัดที่ใช้กันทั่วไปในด้านการให้คะแนนเครดิต (credit scoring) และการสร้างโมเดลความเสี่ยง (risk modeling) โดยเฉพาะในปัญหาการจำแนกประเภทแบบทวิภาค (binary classification) เช่น การทำนายความเสี่ยงในการผิดนัดชำระหนี้ (loan defaults)

สูตร:
𝑊
𝑜
𝐸
𝑗
=
ln
⁡
(
%
𝐺
𝑜
𝑜
𝑑
𝑗
%
𝐵
𝑎
𝑑
𝑗
)
WoE 
j
​
 =ln( 
%Bad 
j
​%Good 
j)

โดยที่:

%
𝐺
𝑜
𝑜
𝑑
𝑗
%Good 
j
​
 : เปอร์เซ็นต์ของการสังเกตการณ์ที่ "ดี" (เช่น สินเชื่อที่ชำระคืนเต็มจำนวน) ในหมวดหมู่หรือช่วง 
j ของคุณลักษณะหนึ่ง

%
𝐵
𝑎
𝑑
𝑗
%Bad 
j
​
 : เปอร์เซ็นต์ของการสังเกตการณ์ที่ "ไม่ดี" (เช่น สินเชื่อที่ผิดนัดชำระ) ในหมวดหมู่หรือช่วง 
j ของคุณลักษณะหนึ่ง

การตีความ:

WoE > 0: หมวดหมู่ 
j มีสัดส่วนของการสังเกตการณ์ที่ดีสูงกว่าการสังเกตการณ์ที่ไม่ดี

WoE < 0: หมวดหมู่ 
j มีสัดส่วนของการสังเกตการณ์ที่ไม่ดีสูงกว่าการสังเกตการณ์ที่ดี

WoE = 0: หมวดหมู่ 
j มีสัดส่วนของการสังเกตการณ์ที่ดีและไม่ดีเท่ากัน

In [99]:
df1['WoE'] = np.log(df1['prop_n_good']/df1['prop_n_bad'])
df1 = df1.sort_values(by=['WoE']).reset_index(drop=True)
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE
0,G,2654,0.780332,0.007115,2071.0,583.0,0.006121,0.016818,-1.010789
1,F,10530,0.789269,0.028228,8311.0,2219.0,0.024562,0.064013,-0.957865
2,E,28612,0.836572,0.076702,23936.0,4676.0,0.070741,0.134891,-0.645448
3,D,61498,0.870662,0.164862,53544.0,7954.0,0.158244,0.229453,-0.371560
4,C,100245,0.903496,0.268733,90571.0,9674.0,0.267674,0.279071,-0.041697
5,B,109730,0.931632,0.294160,102228.0,7502.0,0.302125,0.216414,0.333647
6,A,59759,0.965578,0.160200,57702.0,2057.0,0.170533,0.059339,1.055654

diff_prop_good:

คำอธิบาย: ความแตกต่างแบบสัมบูรณ์ใน prop_good ระหว่างเกรดที่อยู่ติดกันเมื่อจัดเรียงตาม WoE
การใช้งาน: วัดการเปลี่ยนแปลงในสัดส่วนของเงินกู้ดีระหว่างเกรด ช่วยประเมินความเสถียรของค่า WoE

diff_WoE:

คำอธิบาย: ความแตกต่างแบบสัมบูรณ์ใน WoE ระหว่างเกรดที่อยู่ติดกันเมื่อจัดเรียง
การใช้งาน: วัดการเปลี่ยนแปลงใน WoE ระหว่างเกรด การเปลี่ยนแปลงที่มากอาจแสดงให้เห็นถึงการเปลี่ยนแปลงที่สำคัญในพลังการคาดการณ์ระหว่างหมวดหมู่

In [100]:
df1['diff_prop_good'] = df1['prop_good'].diff().abs()
df1['diff_WoE'] = df1['WoE'].diff().abs()

IV:

คำอธิบาย: Information Value สำหรับตัวแปร
การใช้งาน: คำนวณเป็น:
IV
=
∑
(
(
prop_n_good
−
prop_n_bad
)
×
WoE
)
IV=∑((prop_n_good−prop_n_bad)×WoE)
สรุปค่าทั้งหมดเพื่อให้ได้หมายเลขเดียวที่สรุปพลังการคาดการณ์ของตัวแปร ค่าที่สูงกว่า IV มักแสดงถึงตัวแปรที่มีความสามารถในการแยกแยะดีขึ้น

IV สรุปความแข็งแกร่งในการคาดการณ์โดยรวมของตัวแปรประเภทนั้น ๆ

Information Value (IV) คือ ค่าที่ใช้ในการประเมินความสามารถในการคาดการณ์ของตัวแปรในการแยกแยะระหว่างผลลัพธ์ที่ดีและไม่ดีในโมเดลการประเมินความเสี่ยงทางเครดิต โดยเฉพาะในกระบวนการสร้างสกอร์การ์ด (scorecard) และการเลือกฟีเจอร์ที่ใช้ในโมเดล

ความหมายของ IV
ค่าของ IV จะบ่งบอกถึงความสามารถในการคาดการณ์ของตัวแปร ดังนี้:

IV < 0.02: ตัวแปรไม่สำคัญ (not useful)

0.02 ≤ IV < 0.1: ตัวแปรมีความสำคัญน้อย (weak predictor)

0.1 ≤ IV < 0.3: ตัวแปรมีความสำคัญปานกลาง (moderate predictor)

0.3 ≤ IV < 0.5: ตัวแปรมีความสำคัญสูง (strong predictor)

IV ≥ 0.5: ตัวแปรมีความสำคัญมาก (very strong predictor)

การใช้ IV
การเลือกฟีเจอร์: ใช้ในการเลือกฟีเจอร์ที่มีความสามารถในการคาดการณ์สูงสุดในโมเดล
การประเมินคุณภาพ: ช่วยประเมินคุณภาพของตัวแปรในการแยกแยะระหว่างกลุ่มเป้าหมายที่ต่างกัน เช่น เงินกู้ดีและไม่ดี
การสร้างสกอร์การ์ด: ใช้ในการพัฒนาสกอร์การ์ดเพื่อการประเมินความเสี่ยง

In [103]:
df1['IV'] = (df1['prop_n_good'] - df1['prop_n_bad']) * df1['WoE']
df1['IV'] = df1['IV'].sum()
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,G,2654,0.780332,0.007115,2071.0,583.0,0.006121,0.016818,-1.010789,NaN,NaN,0.26292
1,F,10530,0.789269,0.028228,8311.0,2219.0,0.024562,0.064013,-0.957865,0.008937,0.052924,0.26292
2,E,28612,0.836572,0.076702,23936.0,4676.0,0.070741,0.134891,-0.645448,0.047303,0.312417,0.26292
3,D,61498,0.870662,0.164862,53544.0,7954.0,0.158244,0.229453,-0.371560,0.034090,0.273888,0.26292
4,C,100245,0.903496,0.268733,90571.0,9674.0,0.267674,0.279071,-0.041697,0.032834,0.329863,0.26292
5,B,109730,0.931632,0.294160,102228.0,7502.0,0.302125,0.216414,0.333647,0.028136,0.375344,0.26292
6,A,59759,0.965578,0.160200,57702.0,2057.0,0.170533,0.059339,1.055654,0.033946,0.722007,0.26292